In [11]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

## Handling Imbalanced Dataset with Machine Learning

In [12]:
df = pd.read_csv("data/creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [13]:
df.shape

(284807, 31)

In [14]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [15]:
# Check the dependent feature ---> y
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [16]:
# Independent and Dependent Features
# Split into X(features) and y(labels)

X=df.drop("Class",axis=1)
y=df['Class']

## Cross Validation Like KFOLD and Hyperparameter Tuning

In [17]:
# Lets apply a simple ML algorithm 

from sklearn.linear_model import LogisticRegression # Ml algorithm
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report # evaluation methods

from sklearn.model_selection import KFold # cross-validation to help imbalanced datasets
from sklearn.model_selection import GridSearchCV # hyperparameter tuning

In [18]:
log_class = LogisticRegression()

# Hyperparameter tuning
grid = {
    'C':10.0 **np.arange(-2,3), # giving C different values
    'penalty':['l1','l2']
}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [19]:
from sklearn.model_selection import train_test_split

np.random.seed(42)

X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [20]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

C:\Users\HP\Desktop\jupy_sampleProject1\env\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.83016675        nan 0.84794841        nan 0.84744612
        nan 0.84721962        nan 0.84072774]
  warnings.warn(
C:\Users\HP\Desktop\jupy_sampleProject1\env\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [21]:
# Make predictions with the best hyperparameters
y_pred=clf.predict(X_test)

# Evaluate the predictions
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85253    54]
 [   48    88]]
0.9988062216916541
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.62      0.65      0.63       136

    accuracy                           1.00     85443
   macro avg       0.81      0.82      0.82     85443
weighted avg       1.00      1.00      1.00     85443



### The number of 1s are very less compared to the number of 0s, the ratio difference is huge....so the dataset is imbalanced

In [22]:
X_train.shape

(199364, 30)

In [23]:
y_train.value_counts()

0    199008
1       356
Name: Class, dtype: int64

## 1. Under Sampling

0  ----------------      1

10000  -------  100

**undersampling** -> reduce the points of maximum labels

There are a lot of disadvantages in using this method, due to loss of data.

Used: only when u have **small datasets**

In [24]:
y_train.value_counts()

0    199008
1       356
Name: Class, dtype: int64

In [25]:
from collections import Counter
Counter(y_train)

Counter({0: 199008, 1: 356})

In [26]:
# we will reduce 0s by 80%

from imblearn.under_sampling import RandomUnderSampler  
under_sampler = RandomUnderSampler(0.8) 
X_train_ns, y_train_ns = under_sampler.fit_resample(X_train, y_train) # get new data set

print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199008, 1: 356})
The number of classes after fit Counter({0: 445, 1: 356})


C:\Users\HP\Desktop\jupy_sampleProject1\env\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [27]:
# Train model with new dataset(after undersampling)

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [28]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

# As you can see, precision(accuracy) of 1 has gone to hell! Also, there are a lot of false negatives

[[84044  1263]
 [   10   126]]
0.9851011785634868
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     85307
           1       0.09      0.93      0.17       136

    accuracy                           0.99     85443
   macro avg       0.55      0.96      0.58     85443
weighted avg       1.00      0.99      0.99     85443



## 2. Over Sampling

* whichever classess has less number of values, we will impute and increase the values in those classes

In [29]:
from imblearn.over_sampling import RandomOverSampler

os=RandomOverSampler(0.75) # 75%
X_train_ns,y_train_ns = os.fit_resample(X_train,y_train)

print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

C:\Users\HP\Desktop\jupy_sampleProject1\env\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 199008, 1: 356})
The number of classes after fit Counter({0: 199008, 1: 149256})


In [30]:
# Train model with new dataset(after oversampling)

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [31]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

# By oversampling, false negative has been reduced. Also, precision increases.

[[85301     6]
 [   24   112]]
0.9996488887328394
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.95      0.82      0.88       136

    accuracy                           1.00     85443
   macro avg       0.97      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



## 3. SMOTETomek

* it creates more number of points(new points) of the lowest class
* This method takes more time

In [32]:
from imblearn.over_sampling import SMOTE

oversample = SMOTE(0.75)
X_train_ns,y_train_ns = oversample.fit_resample(X_train,y_train)

print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

C:\Users\HP\Desktop\jupy_sampleProject1\env\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 199008, 1: 356})
The number of classes after fit Counter({0: 199008, 1: 149256})


In [33]:
# Train model with new dataset

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [34]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85281    26]
 [   17   119]]
0.9994967405170698
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.82      0.88      0.85       136

    accuracy                           1.00     85443
   macro avg       0.91      0.94      0.92     85443
weighted avg       1.00      1.00      1.00     85443



## 4. Ensemble Techniques

* it creates more number of points(new points) of the lowest class

In [35]:
from imblearn.ensemble import EasyEnsembleClassifier

easy=EasyEnsembleClassifier()
easy.fit(X_train,y_train)

EasyEnsembleClassifier()

In [36]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82087  3220]
 [    8   128]]
0.9622204276535234
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85307
           1       0.04      0.94      0.07       136

    accuracy                           0.96     85443
   macro avg       0.52      0.95      0.53     85443
weighted avg       1.00      0.96      0.98     85443

