Artificial Neural Networks (ANN) are used for Regression and Classification Problems.

To implement Neural Networks, we will use Tensorflow library. 

## Description of the dataset

Banks wants to retain as maximum customers as possible, because they want to earn money. So they want to understand why customers are leaving the bank at a high rate. 

Therefore, to prevent customers from leaving, they want to understand, assess the situation and find preventive measures.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
# check version of tensorflow. Keras library is integrated into Tenserflow
tf.__version__

'2.6.0'

## Part 1 - Data Preprocessing


### Importing the dataset - Binary Classification


In [ ]:
dataset=pd.read_csv("/content/Churn_Modelling.csv")
len(dataset)

10000

### Checking for missing values

In [ ]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

### Create Matrix of Features and Labels

In [ ]:
# Not all columns are redundant. We will not use the redundant columns in our model
# column 0,1,2 are redundant

X = dataset.iloc[:,3:-1].values # independent variables
y = dataset.iloc[:,-1].values # dependent variable

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding Categorical Data

In [ ]:
# There are 2 categorical variables - country and gender.
# So convert by using label encoding - 0 or 1 (Gender), and by using One hot Encoding (1,0,0,...) (Geography)

#### Label Encoding

In [ ]:
# Label Encoding - Gender column 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

# Female = 0, Male = 1 (Chosen by Machine)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### One Hot Encoding

In [ ]:
# One Hot Encoding - Geography column 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Geography - column 1 - [1]
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into Train and Test Set

In [ ]:
from sklearn.model_selection import train_test_split

# Train - 80% data, Test - 20% data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

**Feature Scaling is absolutely important for Neural Networks**

In [ ]:
# Scale all the features of both train and test set (X)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # prevent information leakage
X_test = sc.transform(X_test)

## Part 2 - Building The ANN

### Initialize the ANN

* Initialize the ANN as a sequence of layers

In [ ]:
# Sequential library is a part of Keras library. Keras library is integrated into Tenserflow

ann = tf.keras.models.Sequential() # intialize the network, ann object

### Adding the input layer and the first hidden layer

In [ ]:
# Create the fully connected layer object. Input layer added automatically
# using Dense class from Keras (Tensorflow) - tf.keras.layers 

# how many neurons do we want?
# it is based on experimentation (hyperparameters) 

ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # 6 hidden neurons in 1st hidden layer, 
# rectifier function - 'relu' (activation function)

### Adding the second hidden layer

In [ ]:
# using add method to add a 2nd hidden layer - no. of neurons must be same

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
# change units and activation function

# Binary classification - 0 or 1, so dimension of neuron is 1 (1 output neuron)

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # sigmoid activation function (gives probability)

# for multiclass classification, output layer dimensions will depend on no.of classes

# for binary classification - activation function is 'sigmoid'
# for multiclass classification - activation function is 'softmax'

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
# using optimizer and loss function, with an evaluation metric

# best optimizer - stochastic gradient descent (adam optimizer)
# loss function, i.e. Cost function J theta - difference between prediction and real result

# for binary classification - loss function is 'binary_crossentropy'
# for multiclass classification - loss function is 'categorical_crossentropy'

ann.compile(optimizer = 'adam', loss='binary_crossentropy', metrics= ['accuracy'])

### Training the ANN on the Training Set

In [ ]:
# same fit method, but neural networks will have 2 extra hyperparameters

# 1) batch_size --> no.of predictions to be compared to actual results (default 32)
# 2) no. of epocs --> no. of iterations the neural network is trained (improves accuracy over time) (can't be small)

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6266 - accuracy: 0.6634
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4850 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4548 - accuracy: 0.8004
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4381 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4271 - accuracy: 0.8146
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4174 - accuracy: 0.8198
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4078 - accuracy: 0.8263
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3973 - accuracy: 0.8351
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3862 - accuracy: 0.8388
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3750 - accura

## Part 4 - Making the predictions and evaluating the model

### Prediction of a single customer (single sample/observation)

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [ ]:
# 1 0 0 -> France, 1 --> Male

# 1--> Yes, 0 --> No

In [ ]:
# since we trained our ANN with the scaled value of the features, predict method must be called on these observation on which the same scaling must be applied
# apply sc object on the single obervation

# Output will be probability (due to sigmoid function)

predict_proba = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
predict_proba

array([[0.03779003]], dtype=float32)

In [ ]:
# Will the customer leave the bank?

if predict_proba < 0.5:
  print("Customer will not leave the bank - False")
else:
  print("Customer will leave the bank - True")

Customer will not leave the bank - False


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test results

In [ ]:
# vector of prediction of X_test and y_test

y_pred = ann.predict(X_test)

# Update y_pred with boolean resuts
# > 0.5 --> 1, else --> 0
y_pred = (y_pred > 0.5)

In [ ]:
# Concatenate the 2 vectors (Compare two numerical vectors - estimated and true)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# reshape vector from horizantal to vertical
# axis = 1 for vertical concatenation

# first column --> predicted label (test set), second column --> true label (real ones - train set)

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

confuse_matrix = confusion_matrix(y_test,y_pred) # compare actual labels (test) with predicted labels
print(confuse_matrix)

accuracy_score(y_test, y_pred)

[[1495  100]
 [ 186  219]]


0.857

In [ ]:
# when predict = 0 and actual = 0, we have 1495 samples (correct sammples) - customer stays (actual)
# when predict = 1 and actual = 1, we have 219 samples (correct sammples) - customer leaves (actual)

# (Incorrect predictions)
# false +ve --> when predict = 1 and actual = 0  - customer stays
# false -ve --> when predict = 0 and actual = 1 - customer leaves